export { default as SetupStep1 } from './app/setup/step1.png'
export { default as SetupStep2 } from './app/setup/step2.png'
export { default as SetupStep3 } from './app/setup/step3.png'
export { default as SetupStep4 } from './app/setup/step4.png'
export { default as SetupStep5 } from './app/setup/step5.png'